2023-07-24 21:52:51,121 DEBUG decorator.py Была вызвана функция get_message c параметрами (<socket.socket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 7777), raddr=('127.0.0.1', 51982)>,) , {}. Вызов из модуля common.utils
2023-07-24 21:52:51,121 DEBUG core.py Getting data from client exception.
Traceback (most recent call last):
  File "/home/dilbazi/async_cat/async/lesson3/server/core.py", line 87, in run
    self.process_client_message(get_message(client_with_message), client_with_message)
  File "/home/dilbazi/async_cat/async/lesson3/common/decorator.py", line 36, in log_saver
    ret = func_to_log(*args, **kwargs)
  File "/home/dilbazi/async_cat/async/lesson3/common/utils.py", line 13, in get_message
    response = json.loads(json_response)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-07-24 21:52:51,122 INFO core.py Клиент ('127.0.0.1', 51982) отключился от сервера.
